<?php

return [
    'FindChia' => 'FindChia',
    '#1 Chia pool with fiat or crypto payouts'
    => '#1 Chia pool with fiat or crypto payouts',
    'connect to our pool at this address:'
    => 'connect to our pool at this address:',
    'pool.findchia.com' => 'pool.findchia.com',
    'Industry leading performance with 0% lifetime fee offer (Hurry! We\'ll raise it up to 1% for those who will join us in September) and direct payouts in fiat/crypto.'
    => 'Industry leading performance with 0% lifetime fee offer (Hurry! We\'ll raise it up to 1% for those who will join us in September) and direct payouts in fiat/crypto.',
    'Start Farming' => 'Start Farming',
    'What makes us the best?' => 'What makes us the best?',
    'Airdrops, experience, comfortable fee, fiat & crypto payouts' => 'Airdrops, experience, comfortable fee, fiat & crypto payouts',
    '0% lifetime fee offer is valid for those who join us till the 1st of September 2021. We\'ll raise it up to 1% for those who join later. Stick around for regular airdrops, contests along the way!'
    => '0% lifetime fee offer is valid for those who join us till the 1st of September 2021. We\'ll raise it up to 1% for those who join later. Stick around for regular airdrops, contests along the way!',
    'Years of technical experience with crypto currencies mining and exchanging'
    => 'Years of technical experience with crypto currencies mining and exchanging',
    'Direct payouts' => 'Direct payouts',
    'Not only in crypto but also in fiat' => 'Not only in crypto but also in fiat',
    'Regular airdrops, contests' => 'Regular airdrops, contests',
    'Especially at the beginning' => 'Especially at the beginning',
    '0% lifetime fee' => '0% lifetime fee',
    'We guarantee that those miners who join us till the end of summer will get 0% fee forever, with no limits' => 'We guarantee that those miners who join us till the end of summer will get 0% fee forever, with no limits',
    'Even if you join us after summer you will enjoy a comfortable 1% fee. No hidden commissions, taxes or blockers to receive your earned crypto, as well as fiat soon.'
    => 'Even if you join us after summer you will enjoy a comfortable 1% fee. No hidden commissions, taxes or blockers to receive your earned crypto, as well as fiat soon.',
    'FAQ' => 'FAQ',
    'Login' => 'Login',
    'Registration' => 'Registration',
    'Logout' => 'Logout',
    'Terms of Service' => 'Terms of Service',
    'Pool Capacity Stats' => 'Pool Capacity Stats',
    'Plots NFT' => 'Plots NFT',
    'Bind Plot NFT to Account' => 'Bind Plot NFT to Account',
    'Launcher Id' => 'Launcher Id',
    'First seen' => 'First seen',
    'Hourly' => 'Hourly',
    'Points per hour' => 'Points per hour',
    'Daily' => 'Daily',
    'Points per day' => 'Points per day',
    'Looks like you do not have any plots binded to your account.' => 'Looks like you do not have any plots binded to your account',
    'To bind plots please press the button.' => 'To bind plots please press the button.',
    'Harvester' => 'Harvester',
    'Label' => 'Label',
    'Status' => 'Status',
    'First Seen' => 'First Seen',
    'No points' => 'No points',
    'OK' => 'OK',
    'Never'=>'Never',
    'Less than an hour'=>'Less than an hour',
    'Global Netspace'=>'Global Netspace',
    'Pool Netspace'=>'Pool Netspace',
    'Farmers Total'=>'Farmers Total',
    'Blocks Found'=>'Blocks Found',
    'Last Block Found'=>'Last Block Found',
    'Last Day Growth'=>'Last Day Growth',
    'Win Estimation'=>'Win Estimation',
    'XCH/USDT price'=>'XCH/USDT price',
    'Less than a day'=>'Less than a day',
    'Harvester Failure Notification'=>'Harvester Failure Notification',
    'We\'ll send an email to'=>'We\'ll send an email to',
    'Notify Me!'=>'Notify Me!',
    'Dashboard'=>'Dashboard',
    'Your payout addresses:'=>'Your payout addresses:',
];
