<?php

return [
    'The above error occurred while the Web server was processing your request.' => 'The above error occurred while the Web server was processing your request.',
    'Please contact us if you think this is a server error. Thank you.' => 'Please contact us if you think this is a server error. Thank you.',
    'Please fill out the following fields to login:' => 'Please fill out the following fields to login:',
    'email' => 'Email',
    'password' => 'Password',
    'confirm password' => 'Confirm password',
    'Login' => 'Login',
    'Find Chia - Login' => 'Find Chia - Login',
    'Find Chia - Recovery password' => 'Find Chia - Recovery password',
    'Please enter your email to recovery password:' => 'Please enter your email to recovery password:',
    'Send' => 'Send',
    'Success' => 'Success',
    'Please check your email to proceed with changing your password' => 'Please check your email to proceed with changing your password',
    'Find Chia - Registration' => 'Find Chia - Registration',
    'Please fill out the following fields to registration:' => 'Please fill out the following fields to registration:',
    'Please check your email and confirm account registration. Access to the pool dashboard will be granted after the official Chia pool protocol mainnet launch, and you will be notified at your email address. Happy farming!' => 'Please check your email and confirm account registration. Access to the pool dashboard will be granted after the official Chia pool protocol mainnet launch, and you will be notified at your email address. Happy farming!',
    'Registration' => 'Registration',
    'Save' => 'Save',
    'remember me' => 'remember me',
    'old password' => 'Old password',
    'password reset token' => 'password reset token',
    'hash' => 'hash',
    'Create an account to catch up on your NFT statistic' => 'Create an account to catch up on your NFT statistic',
    'Start farming without registration' => 'Start farming without registration',
    'Just paste this link in your chia client. Check out'=> 'Just paste this link in your chia client. Check out',
    'for more info.' => 'for more info.',
    'Copied' => 'Copied',
    'paste url here' => 'paste url here',
    'Forgot password?' => 'Forgot password?',
    'Recovery password form'=>'Recovery password form',
    'Registration success'=>'Registration success',
    'Recovery password'=>'Recovery password',
    'Change password'=>'Change password',
    'Please fill out the following fields to change password:'=>'Please fill out the following fields to change password:',
    'New password'=>'New password',
    'Confirm new password'=>'Confirm new password',
    'Password changed successfully!'=>'Password changed successfully!',
    'Change Password Success'=>'Change Password Success',
    'Settings'=>'Settings',
    'Get an e-mail notification if Harvester doesn\'t send partials to us in...'=>'Get an e-mail notification if Harvester doesn\'t send partials to us in...',

];
