<?php

return [
    'Find Chia - Terms of Service' => 'Find Chia - Terms of Service',
    'Terms of Service' => 'Terms of Service',
    'General Information' => 'General Information',
    'This Agreement governs your use of findchia.com (the “Pool”). By using the Pool or registering at the Pool\'s website, you agree to be bound by the terms and conditions below. If you do not agree with the terms and conditions in this Agreement you may not use the Pool.'
        => 'This Agreement governs your use of findchia.com (the “Pool”). By using the Pool or registering at the Pool\'s website, you agree to be bound by the terms and conditions below. If you do not agree with the terms and conditions in this Agreement you may not use the Pool.',
    'The Pool Operator may modify this Agreement and any policies affecting the Site at any time. Such modification is effective immediately upon posting to the Pool\'s website or distribution via email. Your continued use of the Pool following any modification to this Agreement shall be deemed an acceptance of all such modifications. Plots rejected by the Pool as invalid are not paid for.'
        => 'The Pool Operator may modify this Agreement and any policies affecting the Site at any time. Such modification is effective immediately upon posting to the Pool\'s website or distribution via email. Your continued use of the Pool following any modification to this Agreement shall be deemed an acceptance of all such modifications. Plots rejected by the Pool as invalid are not paid for.',
    'The Pool is not an e-wallet or a bank. It is forbidden to use Pool accounts for the long-term storage of financial assets. The Pool Operator is not responsible for any loss of assets which are stored on the Pool. It is your responsibility to configure your account so that the assets you farm are regularly transferred to your own secured wallet.'
        => 'The Pool is not an e-wallet or a bank. It is forbidden to use Pool accounts for the long-term storage of financial assets. The Pool Operator is not responsible for any loss of assets which are stored on the Pool. It is your responsibility to configure your account so that the assets you farm are regularly transferred to your own secured wallet.',
    'While the Pool has an excellent uptime record, there is no uptime guarantee. Users are responsible for configuring their farmerts so that they will automatically switch to solo mining and/or to other pools in case of downtime.'
        => 'While the Pool has an excellent uptime record, there is no uptime guarantee. Users are responsible for configuring their farmerts so that they will automatically switch to solo mining and/or to other pools in case of downtime.',
    'Pool accounts are personal, and cannot be sold, traded, bartered or gifted. Multiple accounts controlled by a single entity may be considered as a botnet, and are not welcome. Users suspected of dishonest, fraudulent or illegal activities may be banned without prior notice. In the case of a suspected block withholding attack against the Pool, the Pool Operator may suspend or limit payments to the suspected account(s).'
        => 'Pool accounts are personal, and cannot be sold, traded, bartered or gifted. Multiple accounts controlled by a single entity may be considered as a botnet, and are not welcome. Users suspected of dishonest, fraudulent or illegal activities may be banned without prior notice. In the case of a suspected block withholding attack against the Pool, the Pool Operator may suspend or limit payments to the suspected account(s).',
    'Accounts which are inactive (no significant farming activity) for longer than a year (365 days) may be permanently deleted. Any remaining balance will be considered as a donation to the Pool.'
        => 'Accounts which are inactive (no significant farming activity) for longer than a year (365 days) may be permanently deleted. Any remaining balance will be considered as a donation to the Pool.',
    'Eligibility'
        => 'Eligibility',
    'This Pool is intended solely for users who are eighteen (18) years of age or older. You affirm that you are more than 18 years of age and are competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. You must be 18 years or over to register as a registrant of the Pool. If we discover or have any reason to suspect that you have not reached 18 years of age, then we reserve the right to suspend or terminate your registration to this site immediately and without notice.'
        => 'This Pool is intended solely for users who are eighteen (18) years of age or older. You affirm that you are more than 18 years of age and are competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. You must be 18 years or over to register as a registrant of the Pool. If we discover or have any reason to suspect that you have not reached 18 years of age, then we reserve the right to suspend or terminate your registration to this site immediately and without notice.',
    'Legality' => 'Legality',
    'You agree the Pool cannot be held liable if laws applicable to you restrict or prohibit your participation. The Pool makes no representations or warranties, implicit or explicit, as to your legal right to participate in any interactive services on the Pool nor shall any person affiliated, or claiming affiliation, with the Pool have authority to make any such representations or warranties, and it is your responsibility to ensure that it is permissible to access and use the Pool. The Pool reserves the right to monitor the location from which you access the Pool and to block access from any jurisdiction in which participation is illegal or restricted.'
        => 'You agree the Pool cannot be held liable if laws applicable to you restrict or prohibit your participation. The Pool makes no representations or warranties, implicit or explicit, as to your legal right to participate in any interactive services on the Pool nor shall any person affiliated, or claiming affiliation, with the Pool have authority to make any such representations or warranties, and it is your responsibility to ensure that it is permissible to access and use the Pool. The Pool reserves the right to monitor the location from which you access the Pool and to block access from any jurisdiction in which participation is illegal or restricted.',
    'Questions' => 'Questions',
    'If you have questions or would like additional information, please contact us at: info@findchia.com.'
        => 'If you have questions or would like additional information, please contact us at: info@findchia.com.',
];