<?php

return [
    '#1 Chia pool with fiat or crypto payouts'
        => '#1Chia 哈希池 使用法定货币或加密货币支付',
    'connect to our pool at this address:'
        => '在这个地址连接到我们的哈希池：',
    'pool.findchia.com' => 'pool.findchia.com',
    'Industry leading performance with 0% lifetime fee offer (Hurry! We\'ll raise it up to 1% for those who will join us in September) and direct payouts in fiat/crypto.'
        => '行业领先的表现，提供 0% 的终身费用优惠（快点！我们将为 9 月加入我们的人提高至 1%）和法币/加密货币的直接支付。',
    'Start Farming' => 'Start Farming',
    'What makes us the best?' => '是什么让我们成为最好的？',
    'Airdrops, experience, comfortable fee, fiat & crypto payouts' => '空投，经验，舒适的费用，法定和加密支出',
    '0% lifetime fee offer is valid for those who join us till the 1st of September 2021. We\'ll raise it up to 1% for those who join later. Stick around for regular airdrops, contests along the way!'
        => '2021 年 9 月 1 日之前加入我们的人可享受 0% 的终身费用优惠。我们将为以后加入的人提高至 1%。 坚持定期空投，一路比赛！',
    'Years of technical experience with crypto currencies mining and exchanging'
        => '多年的加密货币挖掘和交换技术经验',
    'Direct payouts' => '直接支付',
    'Not only in crypto but also in fiat' => '不仅在加密中，而且在法币中',
    'Regular airdrops, contests' => '定期空投，竞赛',
    'Especially at the beginning' => '特别是在开始时',
    '0% lifetime fee' => '0%终身费用',
    'We guarantee that those miners who join us till the end of summer will get 0% fee forever, with no limits' => '我们保证那些加入我们直到夏天结束的矿工将永远获得0％的费用，没有限制',
    'Even if you join us after summer you will enjoy a comfortable 1% fee. No hidden commissions, taxes or blockers to receive your earned crypto, as well as fiat soon.'
        => '即使您在夏季后加入我们，您也可以享受1％的舒适费用。 没有隐藏的佣金，税收或阻止者可以很快收到您获得的加密以及法定货币。',
    'FAQ' => '常见问题',
    'Login' => '登录',
    'Registration' => '注册',
    'Logout' => '注销',
    'Terms of Service' => '服务条款',
    'Pool Capacity Stats' => '池容量统计',
    'Plots NFT' => 'Plots NFT',
    'Bind Plot NFT to Account' => '将Plot NFT绑定到帐户',
    'Launcher Id' => '启动器Id',
    'First seen' => '初见',
    'Hourly' => '每小时',
    'Points per hour' => '每小时点数',
    'Daily' => '每日',
    'Points per day' => '每日积分',
    'Looks like you do not have any plots binded to your account.' => '它看起来像你没有任何地块绑定到您的帐户。',
    'To bind plots please press the button.' => '要绑定地块，请按下按钮。',
    'Harvester' => '收割机',
    'Label' => '标签',
    'Status' => '地位',
    'First Seen' => '初见',
    'No points' => '没有积分',
    'OK' => '行',
    'Never'=>'绝不',
    'Less than an hour'=>'不到一个小时',
    'Global Netspace'=>'全球网络空间',
    'Pool Netspace'=>'池网络空间',
    'Farmers Total'=>'农民总数',
    'Blocks Found'=>'找到块',
    'Last Block Found'=>'找到最后一个区块',
    'Last Day Growth'=>'最后一天成长',
    'Win Estimation'=>'获胜估计',
    'XCH/USDT price'=>'XCH/USDT 价钱',
    'Less than a day'=>'不到一天',
    'Harvester Failure Notification'=>'收割机故障通知',
    'We\'ll send an email to'=>'我们将发送电子邮件至',
    'Notify Me!'=>'通知我!',
    'Dashboard'=>'仪表板',
    'Your payout addresses:'=>'您的收款地址：',
];
