<?php

return [
    'The above error occurred while the Web server was processing your request.'
        => '在Web服务器处理您的请求时发生上述错误。',
    'Please contact us if you think this is a server error. Thank you.'
        => '如果您认为这是服务器错误，请与我们联系。 谢谢！.',
    'Please fill out the following fields to login:' => '请填写以下字段登录:',
    'email' => '电子邮件',
    'password' => '密码',
    'confirm password' => '确认密码',
    'Login' => '登录',
    'Find Chia - Login' => 'Find Chia - 登录',
    'Find Chia - Recovery password' => 'Find Chia - 恢复密码',
    'Please enter your email to recovery password:' => '请输入您的电子邮件恢复密码:',
    'Send' => '发送',
    'Success' => '成功',
    'Please check your email to proceed with changing your password'
        => '请检查您的电子邮件以继续更改密码',
    'Find Chia - Registration' => 'Find Chia - 登记',
    'Please fill out the following fields to registration:' => '请填写以下字段进行注册:',
    'Please check your email and confirm account registration. Access to the pool dashboard will be granted after the official Chia pool protocol mainnet launch, and you will be notified at your email address. Happy farming!'
        => '请检查您的电子邮件并确认帐户注册。 在官方Chia pool协议主网启动后，将授予对池控制面板的访问权限，您将收到电子邮件地址的通知。 快乐耕作！',
    'Registration' => '注册',
    'Save' => '保存',
    'remember me' => '记住我',
    'old password' => '旧密码',
    'password reset token' => '密码重置令牌',
    'hash' => '哈希',
    'Create an account to catch up on your NFT statistic' => '创建帐户观看NFT统计',
    'Start farming without registration' => '无需注册即可开始耕作',
    'Just paste this link in your chia client. Check out'=> '只需将此链接粘贴到您的chia客户端中。 退房',
    'for more info.' => '欲了解更多信息.',
    'Copied' => '复制',
    'paste url here' => '在这里粘贴网址',
    'Forgot password?' => '忘记密码？',
    'Recovery password form'=>'恢复密码表格',
    'Registration success'=>'注册成功',
    'Please fill out the following fields to change password:'=>'请填写以下字段以更改密码：',
    'Recovery password'=>'恢复密码',
    'Change password'=>'更改密码',
    'New password'=>'新密码',
    'Confirm new password'=>'确认新密码',
    'Password changed successfully!'=>'密码修改成功！',
    'Change Password Success'=>'更改密码成功',
    'Settings'=>'设置',
    'Get an e-mail notification if Harvester doesn\'t send partials to us in...'=>'如果 Harvester 未在...中向我们发送部分内容，请获取电子邮件通知',
];
