<?php

return [
    '#1 Chia pool with fiat or crypto payouts'
    => '#1 Chia pool mit fiat-oder Krypto Auszahlungen',
    'connect to our pool at this address:'
    => 'Verbinden Sie sich mit unserem Pool unter dieser Adresse:',
    'pool.findchia.com' => 'pool.findchia.com',
    'Industry leading performance with 0% lifetime fee offer (Hurry! We\'ll raise it up to 1% for those who will join us in September) and direct payouts in fiat/crypto.'
    => 'Branchenführende Leistung mit 0 % lebenslangem Gebührenangebot (Beeilung! Wir erhöhen es auf bis zu 1 % für diejenigen, die im September zu uns kommen) und direkten Auszahlungen in Fiat/Krypto.',
    'Start Farming' => 'Start Farming',
    'What makes us the best?' => 'Was macht uns zum Besten?',
    'Airdrops, experience, comfortable fee, fiat & crypto payouts' => 'Airdrops, Erfahrung, komfortable Gebühr, fiat & crypto Auszahlungen',
    '0% lifetime fee offer is valid for those who join us till the 1st of September 2021. We\'ll raise it up to 1% for those who join later. Stick around for regular airdrops, contests along the way!'
    => 'Das Angebot für eine lebenslange Gebühr von 0% gilt für diejenigen, die bis zum 1. September 2021 beitreten. Wir erhöhen sie auf 1% für diejenigen, die später beitreten. Bleiben Sie für regelmäßige Airdrops und Wettbewerbe unterwegs!',
    'Years of technical experience with crypto currencies mining and exchanging'
    => '',
    'Direct payouts' => 'Direkte Auszahlungen',
    'Not only in crypto but also in fiat' => 'Nicht nur in Krypto, sondern auch in Fiat',
    'Regular airdrops, contests' => 'Regelmäßige airdrops, Wettbewerbe',
    'Especially at the beginning' => 'Besonders am Anfang',
    '0% lifetime fee' => '0% lebenslange Gebühr',
    'We guarantee that those miners who join us till the end of summer will get 0% fee forever, with no limits' => 'Wir garantieren, dass die Bergleute, die uns bis zum Ende des Sommers beitreten, für immer 0% Gebühr erhalten, ohne Grenzen',
    'Even if you join us after summer you will enjoy a comfortable % fee. No hidden commissions, taxes or blockers to receive your earned crypto, as well as fiat soon.'
    => 'Auch wenn Sie uns nach dem Sommer beitreten, erhalten Sie eine komfortable Gebühr von 1%. Keine versteckten Provisionen, Steuern oder Blocker, um Ihre verdiente Krypto sowie Fiat bald zu erhalten.',
    'FAQ' => 'FAQ',
    'Login' => 'Login',
    'Registration' => 'Registrierung',
    'Logout' => 'Abmelden',
    'Terms of Service' => 'Servicebedingungen',
    'Pool Capacity Stats' => 'Pool Kapazität Statistik',
    'Plots NFT' => 'Plots NFT',
    'Bind Plot NFT to Account' => 'Binden Sie Plot NFT an Konto',
    'Launcher Id' => 'Launcher Id',
    'First seen' => 'Zuerst gesehen',
    'Hourly' => 'Stündlich',
    'Points per hour' => 'Punkte pro Stunde',
    'Daily' => 'Täglich',
    'Points per day' => 'Punkte pro Tag',
    'Looks like you do not have any plots binded to your account.' => 'Sieht so aus, als hätten Sie keine Grundstücke an Ihr Konto gebunden.',
    'To bind plots please press the button.' => 'Um Plots zu binden, drücken Sie bitte die Taste.',
    'Harvester' => 'Mähdrescher',
    'Label' => 'Etikett',
    'Status' => 'Status',
    'First Seen' => 'Zum ersten Mal gesehen',
    'No points' => 'Keine Punkte',
    'OK' => 'OK',
    'Never'=>'Noch nie',
    'Less than an hour'=>'Weniger als eine Stunde',
    'Global Netspace'=>'Globaler Netzraum',
    'Pool Netspace'=>'Pool Netzraum',
    'Farmers Total'=>'Landwirte insgesamt',
    'Blocks Found'=>'Blöcke gefunden',
    'Last Block Found'=>'Letzter gefundener Block',
    'Last Day Growth'=>'Wachstum am letzten Tag',
    'Win Estimation'=>'Gewinnschätzung',
    'XCH/USDT price'=>'XCH/USDT Preis',
    'Less than a day'=>'Weniger als ein Tag',
    'Harvester Failure Notification'=>'Benachrichtigung über Ernteausfälle',
    'We\'ll send an email to'=>'Wir senden eine E-Mail an',
    'Notify Me!'=>'Benachrichtige mich!',
    'Dashboard'=>'Armaturenbrett',
    'Your payout addresses:'=>'Ihre Auszahlungsadressen',
];
