<?php

return [
    'Find Chia - Terms of Service' => 'Find Chia - Servicebedingungen',
    'Terms of Service' => 'Servicebedingungen',
    'General Information' => 'Allgemeine Informationen',
    'This Agreement governs your use of findchia.com (the “Pool”). By using the Pool or registering at the Pool\'s website, you agree to be bound by the terms and conditions below. If you do not agree with the terms and conditions in this Agreement you may not use the Pool.'
        => 'Diese Vereinbarung regelt Ihre Nutzung von findchia.com (der "Pool"). Durch die Nutzung des Pools oder die Registrierung auf der Website des Pools erklären Sie sich mit den folgenden Bedingungen einverstanden. Wenn Sie mit den Bedingungen dieser Vereinbarung nicht einverstanden sind, dürfen Sie den Pool nicht nutzen.',
    'The Pool Operator may modify this Agreement and any policies affecting the Site at any time. Such modification is effective immediately upon posting to the Pool\'s website or distribution via email. Your continued use of the Pool following any modification to this Agreement shall be deemed an acceptance of all such modifications. Plots rejected by the Pool as invalid are not paid for.'
        => 'Der Poolbetreiber kann diese Vereinbarung und alle Richtlinien, die sich auf die Website auswirken, jederzeit ändern. Eine solche Änderung ist sofort nach der Veröffentlichung auf der Website des Pools oder der Verteilung per E-Mail wirksam. Ihre fortgesetzte Nutzung des Pools nach jeder Änderung dieser Vereinbarung gilt als Annahme aller dieser Änderungen. Grundstücke, die vom Pool als ungültig abgelehnt wurden, werden nicht bezahlt.',
    'The Pool is not an e-wallet or a bank. It is forbidden to use Pool accounts for the long-term storage of financial assets. The Pool Operator is not responsible for any loss of assets which are stored on the Pool. It is your responsibility to configure your account so that the assets you farm are regularly transferred to your own secured wallet.'
        => 'Der Pool ist kein E-Wallet oder eine Bank. Es ist verboten, Poolkonten für die langfristige Speicherung von finanziellen Vermögenswerten zu verwenden. Der Poolbetreiber haftet nicht für Verluste von Vermögenswerten, die im Pool gespeichert sind. Es liegt in Ihrer Verantwortung, Ihr Konto so zu konfigurieren, dass die von Ihnen verwalteten Vermögenswerte regelmäßig in Ihre eigene gesicherte Brieftasche übertragen werden.',
    'While the Pool has an excellent uptime record, there is no uptime guarantee. Users are responsible for configuring their farms so that they will automatically switch to solo mining and/or to other pools in case of downtime.'
        => 'Während der Pool eine ausgezeichnete Betriebszeit hat, gibt es keine Betriebszeitgarantie. Benutzer sind dafür verantwortlich, ihre Farmen so zu konfigurieren, dass sie bei Ausfallzeiten automatisch zu Solo Mining und/oder zu anderen Pools wechseln.',
    'Pool accounts are personal, and cannot be sold, traded, bartered or gifted. Multiple accounts controlled by a single entity may be considered as a botnet, and are not welcome. Users suspected of dishonest, fraudulent or illegal activities may be banned without prior notice. In the case of a suspected block withholding attack against the Pool, the Pool Operator may suspend or limit payments to the suspected account(s).'
        => 'Poolkonten sind persönlich und können nicht verkauft, gehandelt, getauscht oder verschenkt werden. Mehrere Konten, die von einer einzelnen Entität gesteuert werden, können als Botnetz betrachtet werden und sind nicht willkommen. Benutzer, die im Verdacht stehen, unehrlich zu sein, betrügerische oder illegale Aktivitäten können ohne vorherige Ankündigung verboten werden. Im Falle eines mutmaßlichen Block-Quellenangriffs auf den Pool kann der Poolbetreiber Zahlungen an das / die verdächtigen Konten aussetzen oder einschränken.',
    'Accounts which are inactive (no significant farming activity) for longer than a year (365 days) may be permanently deleted. Any remaining balance will be considered as a donation to the Pool.'
        => 'Konten, die länger als ein Jahr (365 Tage) inaktiv sind (keine nennenswerte landwirtschaftliche Tätigkeit), können dauerhaft gelöscht werden. Jeder verbleibende Restbetrag wird als Spende an den Pool betrachtet.',
    'Eligibility'
        => 'Förderfähigkeit',
    'This Pool is intended solely for users who are eighteen (18) years of age or older. You affirm that you are more than 18 years of age and are competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. You must be 18 years or over to register as a registrant of the Pool. If we discover or have any reason to suspect that you have not reached 18 years of age, then we reserve the right to suspend or terminate your registration to this site immediately and without notice.'
        => 'Dieser Pool ist ausschließlich für Benutzer ab 18 Jahren bestimmt. Sie bestätigen, dass Sie älter als 18 Jahre sind und befugt sind, die in diesen Nutzungsbedingungen festgelegten Bedingungen, Verpflichtungen, Zusicherungen, Zusicherungen und Garantien zu erfüllen und diese Nutzungsbedingungen einzuhalten und einzuhalten. Sie müssen mindestens 18 Jahre alt sein, um sich als Registrant des Pools zu registrieren. Wenn wir feststellen oder Grund zu der Annahme haben, dass Sie das 18.Lebensjahr noch nicht erreicht haben, behalten wir uns das Recht vor, Ihre Registrierung auf dieser Website sofort und ohne vorherige Ankündigung auszusetzen oder zu beenden.',
    'Legality' => 'Rechtmäßigkeit',
    'You agree the Pool cannot be held liable if laws applicable to you restrict or prohibit your participation. The Pool makes no representations or warranties, implicit or explicit, as to your legal right to participate in any interactive services on the Pool nor shall any person affiliated, or claiming affiliation, with the Pool have authority to make any such representations or warranties, and it is your responsibility to ensure that it is permissible to access and use the Pool. The Pool reserves the right to monitor the location from which you access the Pool and to block access from any jurisdiction in which participation is illegal or restricted.'
        => 'Sie stimmen zu, dass der Pool nicht haftbar gemacht werden kann, wenn die für Sie geltenden Gesetze Ihre Teilnahme einschränken oder verbieten. Der Pool gibt keine Zusicherungen oder Garantien, weder implizit noch explizit, in Bezug auf Ihr gesetzliches Recht, an interaktiven Diensten im Pool teilzunehmen, noch ist eine Person, die mit dem Pool verbunden ist oder behauptet, mit dem Pool verbunden zu sein, befugt, solche Zusicherungen oder Garantien abzugeben, und es liegt in Ihrer Verantwortung sicherzustellen, dass der Zugriff auf und die Nutzung des Pools zulässig ist. Der Pool behält sich das Recht vor, den Ort zu überwachen, von dem aus Sie auf den Pool zugreifen, und den Zugang von einer Gerichtsbarkeit aus zu sperren, in der die Teilnahme illegal oder eingeschränkt ist.',
    'Questions' => 'Fragestellungen',
    'If you have questions or would like additional information, please contact us at: info@findchia.com.'
        => 'Wenn Sie Fragen haben oder weitere Informationen wünschen, kontaktieren Sie uns bitte unter: info@findchia.com.',
];