<?php

return [
    '#1 Chia pool with fiat or crypto payouts'
    => '#1 Chia pool con pagos fiat o crypto',
    'connect to our pool at this address:'
    => 'conéctese a nuestra hashpool en esta dirección:',
    'pool.findchia.com' => 'pool.findchia.com',
    'Industry leading performance with 0% lifetime fee offer (Hurry! We\'ll raise it up to 1% for those who will join us in September) and direct payouts in fiat/crypto.'
    => 'Rendimiento líder en la industria con una oferta de tarifa de por vida del 0% (¡Deprisa! Lo subiremos hasta el 1% para aquellos que se unirán a nosotros en septiembre) y pagos directos en fiat / cripto.',
    'Start Farming' => 'Empezar',
    'What makes us the best?' => '¿Qué nos hace los mejores?',
    'Airdrops, experience, comfortable fee, fiat & crypto payouts' => 'Airdrops, experiencia, tarifa cómoda, fiat y pagos crypto',
    '0% lifetime fee offer is valid for those who join us till the 1st of September 2021. We\'ll raise it up to 1% for those who join later. Stick around for regular airdrops, contests along the way!'
    => 'La oferta de tarifa de por vida del 0% es válida para aquellos que se unan a nosotros hasta el 1 de septiembre de 2021. La subiremos hasta el 1% para aquellos que se unan más tarde. ¡Quédese para los lanzamientos aéreos regulares, concursos en el camino!',
    'Years of technical experience with crypto currencies mining and exchanging'
    => 'Años de experiencia técnica con la minería y el intercambio de criptomonedas',
    'Direct payouts' => 'Pagos directos',
    'Not only in crypto but also in fiat' => 'No solo en cripto sino también en fiat',
    'Regular airdrops, contests' => 'Lanzamientos aéreos regulares, concursos',
    'Especially at the beginning' => 'Especialmente al principio',
    '0% lifetime fee' => 'Tarifa de por vida del 0%',
    'We guarantee that those miners who join us till the end of summer will get 0% fee forever, with no limits' => 'Garantizamos que aquellos mineros que se unan a nosotros hasta el final del verano recibirán una tarifa del 0% para siempre, sin límites',
    'Even if you join us after summer you will enjoy a comfortable 1% fee. No hidden commissions, taxes or blockers to receive your earned crypto, as well as fiat soon.'
    => 'Incluso si se une a nosotros después del verano, disfrutará de una cómoda tarifa del 1%. No hay comisiones ocultas, impuestos o bloqueadores para recibir su cripto ganado, así como fiat pronto.',
    'FAQ' => 'Preguntas frecuentes',
    'Login' => 'Login',
    'Registration' => 'Registro',
    'Logout' => 'Logout',
    'Terms of Service' => 'Condiciones de Servicio',
    'Pool Capacity Stats' => 'Pool Capacidad Estadística',
    'Plots NFT' => 'Plots NFT',
    'Bind Plot NFT to Account' => 'Enlazar la Plot NFT a la Cuenta',
    'Launcher Id' => 'Id del Lanzador',
    'First seen' => 'Visto por primera vez',
    'Hourly' => 'Por hora',
    'Points per hour' => 'Puntos por hora',
    'Daily' => 'Diario',
    'Points per day' => 'Puntos por día',
    'Looks like you do not have any plots binded to your account.' => 'Parece que no tiene ninguna trama vinculada a su cuenta.',
    'To bind plots please press the button.' => 'Para enlazar gráficos, pulse el botón.',
    'Harvester' => 'Segadora',
    'Label' => 'Etiqueta',
    'Status' => 'Estado',
    'First Seen' => 'Visto por primera vez',
    'No points' => 'Sin puntos',
    'OK' => 'OK',
    'Never'=>'Nunca',
    'Less than an hour'=>'Menos de una hora',
    'Global Netspace'=>'Netspace global',
    'Pool Netspace'=>'Pool Netspace',
    'Farmers Total'=>'Farmers Total',
    'Blocks Found'=>'Blocks Encontrada',
    'Last Block Found'=>'Último bloque encontrado',
    'Last Day Growth'=>'Crecimiento del último día',
    'Win Estimation'=>'Estimación de beneficios',
    'XCH/USDT price'=>'XCH/USDT precio',
    'Less than a day'=>'Menos de un día',
    'Harvester Failure Notification'=>'Notificación de falla de Harvester',
    'We\'ll send an email to'=>'Enviaremos un correo electrónico a',
    'Notify Me!'=>'¡Notificarme!',
    'Dashboard'=>'Tablero',
    'Your payout addresses:'=>'Sus direcciones de pago',
];
