<?php

return [
    'The above error occurred while the Web server was processing your request.' => 'El error anterior ocurrió mientras el servidor Web estaba procesando su solicitud.',
    'Please contact us if you think this is a server error. Thank you.' => 'Pónte en contacto con nosotros si crees que un error del servidor ocurre. Gracias.',
    'Please fill out the following fields to login:' => 'Por favor, rellena los siguientes campos para iniciar la sesión.',
    'email' => 'Correo',
    'password' => 'Contraseña',
    'confirm password' => 'Confirmar contraseña',
    'Login' => 'Login',
    'Find Chia - Login' => 'Find Chia - Login ',
    'Find Chia - Recovery password' => 'Find Chia - Contraseña de recuperación ',
    'Please enter your email to recovery password:' => 'Por favor, introduzca tu correo electrónico a la contraseña de recuperación:',
    'Send' => 'Enviar',
    'Success' => 'Exito',
    'Please check your email to proceed with changing your password' => 'Por favor, revisa tu correo electrónico para proceder con el cambio de su contraseña',
    'Find Chia - Registration' => 'Find Chia - Registro',
    'Please fill out the following fields to registration:' => 'Por favor, rellena los siguientes campos para registrarse:',
    'Please check your email and confirm account registration. Access to the pool dashboard will be granted after the official Chia pool protocol mainnet launch, and you will be notified at your email address. Happy farming!' => 'Por favor, revise su correo electrónico y confirme el registro de la cuenta. El acceso al panel de control del grupo se otorgará después del lanzamiento oficial de la red principal del protocolo del grupo Chia, y se le notificará a su dirección de correo electrónico. Feliz agricultura!',
    'Registration' => 'Registro',
    'Save' => 'Guardar',
    'remember me' => 'Recuérdame',
    'old password' => 'Contraseña antigua',
    'password reset token' => 'Token de restablecimiento de contraseña',
    'hash' => 'Hash',
    'Create an account to catch up on your NFT statistic' => 'Crear cuenta para ver estadísticas de NFT',
    'Start farming without registration' => 'Comience a cultivar sin registro',
    'Just paste this link in your chia client. Check out'=> 'Solo pega este enlace en tu cliente de chia. Salida',
    'for more info.' => 'para más información.',
    'Copied' => 'Copiar',
    'paste url here' => 'pegar URL aquí',
    'Forgot password?' => '¿Se te olvidó tu contraseña?',
    'Recovery password form'=>'Formulario de recuperación de contraseña',
    'Registration success'=>'Registración exitosa',
    'Please fill out the following fields to change password:'=>'Complete los siguientes campos para cambiar la contraseña:',
    'Recovery password'=>'Contraseña de recuperación',
    'Change password'=>'Cambiar la contraseña',
    'New password'=>'Nueva contraseña',
    'Confirm new password'=>'Confirmar nueva contraseña',
    'Password changed successfully!'=>'¡Contraseña cambiada con éxito!',
    'Change Password Success'=>'Cambiar contraseña correctamente',
    'Settings'=>'Ajustes',
    'Get an e-mail notification if Harvester doesn\'t send partials to us in...'=>'Reciba una notificación por correo electrónico si Harvester no nos envía parciales en ...',
];
