<?php

return [
    'Find Chia - Terms of Service' => 'Find Chia - ',
    'Terms of Service' => 'Condiciones de Servicio',
    'General Information' => 'Información general',
    'This Agreement governs your use of findchia.com (the “Pool”). By using the Pool or registering at the Pool\'s website, you agree to be bound by the terms and conditions below. If you do not agree with the terms and conditions in this Agreement you may not use the Pool.'
    => 'Este Acuerdo rige tu uso de findchia.com (el "Pool"). Al utilizar el Pool o registrarse en el sitio web del Pool, tú aceptas estar sujeto a los términos y condiciones que se indican a continuación. Si no estás de acuerdo con los términos y condiciones de este Acuerdo, no podrás utilizar el Pool.',
    'The Pool Operator may modify this Agreement and any policies affecting the Site at any time. Such modification is effective immediately upon posting to the Pool\'s website or distribution via email. Your continued use of the Pool following any modification to this Agreement shall be deemed an acceptance of all such modifications. Plots rejected by the Pool as invalid are not paid for.'
    => 'El Operador del Pool puede modificar este Acuerdo y cualquiera política que afecte al Sitio en cualquier momento. Dicha modificación entra en vigencia inmediatamente después de tu publicación en el sitio web del Pool o tu distribución por correo electrónico. Tu uso continuado del Pool después de cualquiera modificación a este Acuerdo se considerará una aceptación de dichas modificaciones. Los Plots rechazados por el Pool como inválidas no se pagan.',
    'The Pool is not an e-wallet or a bank. It is forbidden to use Pool accounts for the long-term storage of financial assets. The Pool Operator is not responsible for any loss of assets which are stored on the Pool. It is your responsibility to configure your account so that the assets you farm are regularly transferred to your own secured wallet.'
    => 'El Pool no es una billetera electrónica ni un banco. Está prohibido utilizar cuentas del Pool para el almacenamiento a largo plazo de activos financieros. El operador del Pool no es responsable de ninguna pérdida de activos almacenados en el Pool. Es tu responsabilidad configurar tu cuenta para que los activos que acumulas se transfieran regularmente a tu propia billetera segura.',
    'While the Pool has an excellent uptime record, there is no uptime guarantee. Users are responsible for configuring their farmerts so that they will automatically switch to solo mining and/or to other pools in case of downtime.'
    => 'Mientras el  Pool tiene un excelente registro de tiempo de actividad, no hay garantía de tiempo de actividad. Los usuarios son responsables de configurar sus granjas para que cambien automáticamente a la minería individual y/o a otros Pooles en caso de tiempo de inactividad.',
    'Pool accounts are personal, and cannot be sold, traded, bartered or gifted. Multiple accounts controlled by a single entity may be considered as a botnet, and are not welcome. Users suspected of dishonest, fraudulent or illegal activities may be banned without prior notice. In the case of a suspected block withholding attack against the Pool, the Pool Operator may suspend or limit payments to the suspected account(s).'
    => 'Las cuentas de grupo son personales y no se pueden vender, intercambiar ni regalar. Varias cuentas controladas por una sola entidad pueden considerarse como una botnet y som indeseables. Los usuarios sospechosos de actividades deshonestas, fraudulentas o ilegales pueden ser prohibidos sin previo aviso. En el caso de un supuesto ataque de retención de bloque contra el Pool, el Operador del Pool puede suspender o limitar los pagos a las cuentas sospechosas.',
    'Accounts which are inactive (no significant farming activity) for longer than a year (365 days) may be permanently deleted. Any remaining balance will be considered as a donation to the Pool.'
    => 'Las cuentas que estén inactivas (sin actividad significativa) durante más de un año (365 días) pueden ser eliminadas de forma permanente. Cualquier saldo restante se considerará una donación al Pool.',
    'Eligibility'
    => 'Elegibilidad',
    'This Pool is intended solely for users who are eighteen (18) years of age or older. You affirm that you are more than 18 years of age and are competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. You must be 18 years or over to register as a registrant of the Pool. If we discover or have any reason to suspect that you have not reached 18 years of age, then we reserve the right to suspend or terminate your registration to this site immediately and without notice.'
    => 'Este grupo está destinado únicamente a usuarios que tienen dieciocho (18) años de edad o más. Tú afirmas que tienes más que 18 años de edad y que eres competente para aceptar los términos, condiciones, obligaciones, afirmaciones, representaciones y garantías establecidas en estos Términos de servicio, y para atacar y cumplir con estos Términos de servicio. Debes tener 18 años o más para registrarse como registrante del Pool. Si descubrimos o tenemos alguna razón para sospechar que no has cumplido los 18 años de edad, nos reservamos el derecho de suspender o cancelar tu registro en este sitio inmediatamente y sin previo aviso.',
    'Legality' => 'Legalidad',
    'You agree the Pool cannot be held liable if laws applicable to you restrict or prohibit your participation. The Pool makes no representations or warranties, implicit or explicit, as to your legal right to participate in any interactive services on the Pool nor shall any person affiliated, or claiming affiliation, with the Pool have authority to make any such representations or warranties, and it is your responsibility to ensure that it is permissible to access and use the Pool. The Pool reserves the right to monitor the location from which you access the Pool and to block access from any jurisdiction in which participation is illegal or restricted.'
    => 'Tú aceptas que el Pool no se hace responsable si las leyes aplicables a ti restringen o prohíben tu participación. El Pool no hace representaciones ni garantías, implícitas o explícitas, en cuanto a tu derecho legal a participar en cualquier servicio interactivo en el Pool, ni ninguna persona afiliada o que reclame afiliación con el Pool tendrá autoridad para hacer tales representaciones o garantías, y Es tu responsabilidad asegurarse de que estás permitido acceder y utilizar el Pool. The Pool se reserva el derecho de monitorear la ubicación desde la cual accede al Pool y bloquear el acceso desde cualquier jurisdicción en la que la participación sea ilegal o restringida.',
    'Questions' => 'Pregunta',
    'If you have questions or would like additional information, please contact us at: info@findchia.com.'
    => 'Si tienes preguntas o deseas información adicional, contáctanos en: info@findchia.com.',
];