<?php

return [
    '#1 Chia pool with fiat or crypto payouts'
    => '#1 pool de Chia avec des paiements fiat ou crypto',
    'connect to our pool at this address:'
    => 'connectez-vous à notre hashpool à cette adresse:',
    'pool.findchia.com' => '',
    'Industry leading performance with 0% lifetime fee offer (Hurry! We\'ll raise it up to 1% for those who will join us in September) and direct payouts in fiat/crypto.'
    => 'Des performances de pointe avec une offre de frais à vie de 0% (dépêchez-vous! Nous l\'augmenterons jusqu\'à 1% pour ceux qui nous rejoindront en septembre) et des paiements directs en fiat/crypto.',
    'Start Farming' => 'Commencer',
    'What makes us the best?' => 'Qu\'est-ce qui fait de nous les meilleurs?',
    'Airdrops, experience, comfortable fee, fiat & crypto payouts' => 'Largages aériens, expérience, frais confortables, paiements fiat et crypto',
    '0% lifetime fee offer is valid for those who join us till the 1st of September 2021. We\'ll raise it up to 1% for those who join later. Stick around for regular airdrops, contests along the way!'
    => 'L\'offre de frais à vie de 0% est valable pour ceux qui nous rejoignent jusqu\'au 1er septembre 2021. Nous l\'augmenterons jusqu\'à 1% pour ceux qui adhèrent plus tard. Restez dans les parages pour des parachutages réguliers, des concours en cours de route !',
    'Years of technical experience with crypto currencies mining and exchanging'
    => 'Années d\'expérience technique avec l\'extraction et l\'échange de crypto-monnaies',
    'Direct payouts' => 'Paiements directs',
    'Not only in crypto but also in fiat' => 'Non seulement en crypto mais aussi en fiat',
    'Regular airdrops, contests' => 'Parachutages réguliers, concours',
    'Especially at the beginning' => 'Surtout au début',
    '0% lifetime fee' => 'Frais à vie de 0%',
    'We guarantee that those miners who join us till the end of summer will get 0% fee forever, with no limits' => 'Nous garantissons que les mineurs qui nous rejoignent jusqu\'à la fin de l\'été recevront des frais de 0% pour toujours, sans limites',
    'Even if you join us after summer you will enjoy a comfortable 1% fee. No hidden commissions, taxes or blockers to receive your earned crypto, as well as fiat soon.'
    => 'Même si vous nous rejoignez après l\'été, vous bénéficierez de frais confortables de 1%. Pas de commissions cachées, taxes ou bloqueurs pour recevoir votre crypto gagné, ainsi que fiat bientôt.',
    'FAQ' => 'FAQ',
    'Login' => 'Connexion',
    'Registration' => 'Enregistrement',
    'Logout' => 'Déconnexion',
    'Terms of Service' => 'Conditions d\'utilisation',
    'Pool Capacity Stats' => 'Statistiques de Capacité du Pool',
    'Plots NFT' => 'Plots NFT',
    'Bind Plot NFT to Account' => 'Lier le Plot NFT au Compte',
    'Launcher Id' => 'Id du Lanceur',
    'First seen' => 'Première vue',
    'Hourly' => 'Horaire',
    'Points per hour' => 'Points par heure',
    'Daily' => 'Quotidien',
    'Points per day' => 'Points par jour',
    'Looks like you do not have any plots binded to your account.' => 'On dirait que vous n\'avez pas de parcelles liées à votre compte.',
    'To bind plots please press the button.' => 'Pour lier des tracés, appuyez sur le bouton.',
    'Harvester' => 'Moissonneuse',
    'Label' => 'Étiqueter',
    'Status' => 'Statut',
    'First Seen' => 'Vu la première fois',
    'No points' => 'Aucun point',
    'OK' => 'le bien',
    'Never'=>'Jamais',
    'Less than an hour'=>'Moins d\'une heure',
    'Global Netspace'=>'Espace réseau mondial',
    'Pool Netspace'=>'Pool Netspace',
    'Farmers Total'=>'Farmers Totale',
    'Blocks Found'=>'Blocks Trouvés',
    'Last Block Found'=>'Dernier Block Trouvée',
    'Last Day Growth'=>'Last Day Growth',
    'Win Estimation'=>'Estimation des gains',
    'XCH/USDT price'=>'XCH/USDT le prix',
    'Less than a day'=>'Moins d\'un jour',
    'Harvester Failure Notification'=>'Notification d\'échec de la récolteuse',
    'We\'ll send an email to'=>'Nous enverrons un e-mail à',
    'Notify Me!'=>'Prévenez-moi!',
    'Dashboard'=>'Tableau de bord',
    'Your payout addresses:'=>'Vos adresses de paiement',
];
