<?php

return [
    'The above error occurred while the Web server was processing your request.'
        => 'L\'erreur ci-dessus s\'est produite pendant que le serveur Web traitait votre demande',
    'Please contact us if you think this is a server error. Thank you.'
        => 'Veuillez nous contacter si vous pensez qu\'il s\'agit d\'une erreur de serveur. Merci.',
    'Please fill out the following fields to login:' => 'Veuillez remplir les champs suivants pour vous connecter:',
    'email' => 'courriel',
    'password' => 'mot de passe',
    'confirm password' => 'Confirm mot de passe',
    'Login' => 'Connexion',
    'Find Chia - Login' => 'Find Chia - Connexion',
    'Find Chia - Recovery password' => 'Find Chia - Mot de passe de récupération',
    'Please enter your email to recovery password:' => 'Veuillez entrer votre email pour récupérer le mot de passe:',
    'Send' => 'Envoyer',
    'Success' => 'Succès',
    'Please check your email to proceed with changing your password'
        => 'Veuillez vérifier votre e-mail pour procéder à la modification de votre mot de passe',
    'Find Chia - Registration' => 'Find Chia - Enregistrement',
    'Please fill out the following fields to registration:' => 'Veuillez remplir les champs suivants pour vous inscrire:',
    'Please check your email and confirm account registration. Access to the pool dashboard will be granted after the official Chia pool protocol mainnet launch, and you will be notified at your email address. Happy farming!'
        => 'Veuillez vérifier votre adresse e-mail et confirmer l\'enregistrement du compte. L\'accès au tableau de bord du pool sera accordé après le lancement officiel du protocole Chia pool mainnet, et vous serez averti à votre adresse e-mail. Bonne agriculture!',
    'Registration' => 'Enregistrement',
    'Save' => 'Enregistrer',
    'remember me' => 'Se souvenir de moi',
    'old password' => 'Ancien mot de passe',
    'password reset token' => 'Jeton de réinitialisation du mot de passe',
    'hash' => 'Hash',
    'Create an account to catch up on your NFT statistic' => 'Créer un compte pour regarder NFT statistic',
    'Start farming without registration' => 'Commencer l\'agriculture sans inscription',
    'Just paste this link in your chia client. Check out'=> 'Collez simplement ce lien dans votre client chia. Découvrez',
    'for more info.' => 'pour plus d\'informations.',
    'Copied' => 'Copier',
    'paste url here' => 'collez l\'url ici',
    'Forgot password?' => 'Mot de passe oublié?',
    'Recovery password form'=>'Formulaire de récupération de mot de passe',
    'Registration success'=>'Inscription réussie',
    'Please fill out the following fields to change password:'=>'Veuillez remplir les champs suivants pour changer le mot de passe:',
    'Recovery password'=>'Mot de passe de récupération',
    'Change password'=>'Changer le mot de passe',
    'New password'=>'Nouveau mot de passe',
    'Confirm new password'=>'Confirmer le nouveau mot de passe',
    'Password changed successfully!'=>'Le mot de passe a été changé avec succès!',
    'Change Password Success'=>'Changement de mot de passe réussi',
    'Settings'=>'Paramètres',
    'Get an e-mail notification if Harvester doesn\'t send partials to us in...'=>'Recevez une notification par e-mail si Harvester ne nous envoie pas de partiels dans...',
];
