<?php

return [
    'Find Chia - Terms of Service' => 'Find Chia - Conditions d\'utilisation',
    'Terms of Service' => 'Conditions d\'utilisation',
    'General Information' => 'Informations Générales',
    'This Agreement governs your use of findchia.com (the “Pool”). By using the Pool or registering at the Pool\'s website, you agree to be bound by the terms and conditions below. If you do not agree with the terms and conditions in this Agreement you may not use the Pool.'
        => 'Cet accord régit votre utilisation de findchia.com (la "hashpool"). En utilisant la hashpool ou en vous inscrivant sur le site Web de la hashpool, vous acceptez d\'être lié par les termes et conditions ci-dessous. Si vous n\'êtes pas d\'accord avec les termes et conditions du présent Accord, vous ne pouvez pas utiliser le Pool.',
    'The Pool Operator may modify this Agreement and any policies affecting the Site at any time. Such modification is effective immediately upon posting to the Pool\'s website or distribution via email. Your continued use of the Pool following any modification to this Agreement shall be deemed an acceptance of all such modifications. Plots rejected by the Pool as invalid are not paid for.'
        => 'L\'Exploitant du Pool peut modifier le présent Contrat et toute politique affectant le Site à tout moment. Cette modification entre en vigueur dès sa publication sur le site Web de la hashpool ou sa distribution par courrier électronique. Votre utilisation continue du Pool après toute modification du présent Contrat sera considérée comme une acceptation de toutes ces modifications. Les parcelles rejetées par le Pool comme invalides ne sont pas payées.',
    'The Pool is not an e-wallet or a bank. It is forbidden to use Pool accounts for the long-term storage of financial assets. The Pool Operator is not responsible for any loss of assets which are stored on the Pool. It is your responsibility to configure your account so that the assets you farm are regularly transferred to your own secured wallet.'
        => 'La hashpool\'est pas un porte-monnaie électronique ou une banque. Il est interdit d\'utiliser des comptes communs pour le stockage à long terme des actifs financiers. L\'Opérateur du Pool n\'est pas responsable de toute perte d\'actifs qui sont stockés sur le Pool. Il est de votre responsabilité de configurer votre compte afin que les actifs que vous exploitez soient régulièrement transférés dans votre propre portefeuille sécurisé.',
    'While the Pool has an excellent uptime record, there is no uptime guarantee. Users are responsible for configuring their farms so that they will automatically switch to solo mining and/or to other pools in case of downtime.'
        => 'Bien que la hashpool ait un excellent record de disponibilité, il n\'y a aucune garantie de disponibilité. Les utilisateurs sont responsables de la configuration de leurs fermes afin qu\'elles basculent automatiquement vers le minage en solo et/ou vers d\'autres pools en cas de temps d\'arrêt.',
    'Pool accounts are personal, and cannot be sold, traded, bartered or gifted. Multiple accounts controlled by a single entity may be considered as a botnet, and are not welcome. Users suspected of dishonest, fraudulent or illegal activities may be banned without prior notice. In the case of a suspected block withholding attack against the Pool, the Pool Operator may suspend or limit payments to the suspected account(s).'
        => 'Les comptes de pool sont personnels et ne peuvent pas être vendus, échangés, troqués ou donnés. Plusieurs comptes contrôlés par une seule entité peuvent être considérés comme un botnet et ne sont pas les bienvenus. Les utilisateurs soupçonnés d\'activités malhonnêtes, frauduleuses ou illégales peuvent être interdits sans préavis. Dans le cas d\'une attaque suspectée de retenue de bloc contre le Pool, l\'Opérateur du Pool peut suspendre ou limiter les paiements sur le ou les comptes suspects.',
    'Accounts which are inactive (no significant farming activity) for longer than a year (365 days) may be permanently deleted. Any remaining balance will be considered as a donation to the Pool.'
        => 'Les comptes inactifs (aucune activité agricole significative) pendant plus d\'un an (365 jours) peuvent être définitivement supprimés. Tout solde restant sera considéré comme un don à la Cagnotte.',
    'Eligibility'
        => 'Admissibilité',
    'This Pool is intended solely for users who are eighteen (18) years of age or older. You affirm that you are more than 18 years of age and are competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. You must be 18 years or over to register as a registrant of the Pool. If we discover or have any reason to suspect that you have not reached 18 years of age, then we reserve the right to suspend or terminate your registration to this site immediately and without notice.'
        => 'Ce pool est destiné uniquement aux utilisateurs âgés de dix-huit (18) ans ou plus. Vous affirmez que vous avez plus de 18 ans et que vous êtes compétent pour accepter les termes, conditions, obligations, affirmations, déclarations et garanties énoncés dans les présentes Conditions d\'utilisation, et pour vous conformer aux présentes Conditions d\'utilisation. Vous devez avoir 18 ans ou plus pour vous inscrire en tant que titulaire du pool. Si nous découvrons ou avons des raisons de soupçonner que vous n\'avez pas atteint l\'âge de 18 ans, nous nous réservons le droit de suspendre ou de résilier votre inscription à ce site immédiatement et sans préavis.',
    'Legality' => 'Légalité',
    'You agree the Pool cannot be held liable if laws applicable to you restrict or prohibit your participation. The Pool makes no representations or warranties, implicit or explicit, as to your legal right to participate in any interactive services on the Pool nor shall any person affiliated, or claiming affiliation, with the Pool have authority to make any such representations or warranties, and it is your responsibility to ensure that it is permissible to access and use the Pool. The Pool reserves the right to monitor the location from which you access the Pool and to block access from any jurisdiction in which participation is illegal or restricted.'
        => 'Vous convenez que le Pool ne peut être tenu responsable si les lois applicables à vous restreignent ou interdisent votre participation. Le Pool ne fait aucune déclaration ou garantie, implicite ou explicite, quant à votre droit légal de participer à des services interactifs sur le Pool et toute personne affiliée ou revendiquant une affiliation avec le Pool n\'a pas le pouvoir de faire de telles déclarations ou garanties, et il est de votre responsabilité de vous assurer qu\'il est permis d\'accéder Le Pool se réserve le droit de surveiller l\'emplacement à partir duquel vous accédez au Pool et de bloquer l\'accès à partir de toute juridiction dans laquelle la participation est illégale ou restreinte.',
    'Questions' => 'Question',
    'If you have questions or would like additional information, please contact us at: info@findchia.com.'
        => 'Si vous avez des questions ou souhaitez des informations supplémentaires, veuillez nous contacter à: info@findchia.com.',
];