<?php

return [
    '#1 Chia pool with fiat or crypto payouts'
        => '#1 Chia pool с выплатами в фиат либо в криптовалюте',
    'connect to our pool at this address:'
        => 'подключиться к нашему пулу по этому адресу:',
    'pool.findchia.com' => '',
    'Industry leading performance with 0% lifetime fee offer (Hurry! We\'ll raise it up to 1% for those who will join us in September) and direct payouts in fiat/crypto.'
        => 'Занимая лидирующию позицию в отрасли, мы предлагаем пожизненную комиссию в 0 % (Комиссия 1% для всех кто подключился позднее 1 сентября 2021) и выплаты в фиат либо в криптовалюте',
    'Start Farming' => 'Начать фармить',
    'What makes us the best?' => 'Что отличает нас от других?',
    'Airdrops, experience, comfortable fee, fiat & crypto payouts' => 'Аирдропы, многолетний опыт в отрасли, выгодная комиссия, выплаты в фиате и в крипте',
    '0% lifetime fee offer is valid for those who join us till the 1st of September 2021. We\'ll raise it up to 1% for those who join later. Stick around for regular airdrops, contests along the way!'
        => 'Предложение с пожизненной 0% комиссией действительно для тех, кто присоединится к нам до 1 сентября 2021 года. Мы поднимем ее до 1% для тех, кто присоединится позднее.',
    'Years of technical experience with crypto currencies mining and exchanging'
    => 'Лет опыта с криптовалютами, майнингом и криптовалютными биржами',
    'Direct payouts' => 'Прямые выплаты',
    'Not only in crypto but also in fiat' => 'В крипте и в фиат',
    'Regular airdrops, contests' => 'Регулярная раздача токенов, контесты',
    'Especially at the beginning' => 'Гарантировано на начальных этапах',
    '0% lifetime fee' => 'Комиссия в 0 %',
    'We guarantee that those miners who join us till the end of summer will get 0% fee forever, with no limits' => 'Мы гарантируем пожизненную комиссию в 0 % без каких-либо ограничений тем майнерам, которые присоединятся к нам до конца лета',
    'Even if you join us after summer you will enjoy a comfortable 1% fee. No hidden commissions, taxes or blockers to receive your earned crypto, as well as fiat soon.'
    => 'Даже если вы присоединитесь к нам после окончания лета, вы оцените по достоинству выгодную комиссию в 1 %. Никаких скрытых комиссий, налогов или блокировок при выводе выплат в крипту или фиат',
    'FAQ' => 'FAQ',
    'Login' => 'Вход',
    'Registration' => 'Регистрация',
    'Logout' => 'Выход',
    'Terms of Service' => 'Условия использования',
    'Pool Capacity Stats' => 'Объем пула',
    'Plots NFT' => 'NFT Плоты',
    'Bind Plot NFT to Account' => 'Привязать Plot NFT к учетной записи',
    'Launcher Id' => 'Launcher Id',
    'First seen' => 'Впервые увидено',
    'Hourly' => 'Почасовой',
    'Points per hour' => 'Пойнты за час',
    'Daily' => 'Ежедневно',
    'Points per day' => 'Пойнты за день',
    'Looks like you do not have any plots binded to your account.' => 'Похоже, у вас еще нет плотов, привязанных к Вашему аккаунту.',
    'To bind plots please press the button.' => 'Нажмите на кнопку для осуществления привязки.',
    'Harvester' => 'Харвестер',
    'Label' => 'Название',
    'Status' => 'Статус',
    'First Seen' => 'Дата создания',
    'No points' => 'No points',
    'OK' => 'OK',
    'Never' => 'Никогда',
    'Less than an hour' => 'Менее чем за час',
    'Global Netspace' => 'Общая сеть',
    'Pool Netspace' => 'Объём пула',
    'Farmers Total' => 'Всего фармеров',
    'Blocks Found' => 'Блоков найдено',
    'Last Block Found' => 'Последний блок',
    'Last Day Growth' => 'Прирост за сутки',
    'Win Estimation' => 'Время до выигрыша',
    'XCH/USDT price' => 'XCH/USDT цена',
    'Less than a day'=>'Менее чем за час',
    'Harvester Failure Notification'=>'Уведомление о сбое Харвестера',
    'We\'ll send an email to'=>'Мы вышлем email на',
    'Notify Me!'=>'Уведомить меня!',
    'Dashboard'=>'Информационная панель',
    'Your payout addresses:'=>'Ваши адреса для выплат:',
    'Timezone settings'=>'Настройки тайм зоны',
    'hours'=>'часы',
    'Estimated farm size'=>'Предполагаемый размер фермы',
    'Farm size'=>'Размер фермы',
    'Payouts'=>'Выплаты',
];
