<?php

return [
    'Find Chia - Terms of Service' => '',
    'Terms of Service' => 'Условия использования',
    'General Information' => 'Основная информация',
    'This Agreement governs your use of findchia.com (the “Pool”). By using the Pool or registering at the Pool\'s website, you agree to be bound by the terms and conditions below. If you do not agree with the terms and conditions in this Agreement you may not use the Pool.'
        => 'Настоящее Соглашение регулирует использование вами findchia.com (the “Pool”). Используя пул или регистрируясь на веб-сайте пула, Вы соглашаетесь соблюдать приведенные ниже положения и условия. Если Вы не согласны с условиями Настоящего Соглашения, Вы не можете использовать пул.',
    'The Pool Operator may modify this Agreement and any policies affecting the Site at any time. Such modification is effective immediately upon posting to the Pool\'s website or distribution via email. Your continued use of the Pool following any modification to this Agreement shall be deemed an acceptance of all such modifications. Plots rejected by the Pool as invalid are not paid for.'
        => 'Оператор пула может в любое время изменить Настоящее Соглашение и любую политику, влияющую на сайт. Такое изменение вступает в силу незамедлительно после публикации на веб-сайте пула или рассылки по электронной почте. Дальнейшее использование вами пула после внесения любых изменений в Настоящее Соглашение будет считаться принятием всех таких изменений. Плоты, отклоненные пулом как недействительные, не оплачиваются.',
    'The Pool is not an e-wallet or a bank. It is forbidden to use Pool accounts for the long-term storage of financial assets. The Pool Operator is not responsible for any loss of assets which are stored on the Pool. It is your responsibility to configure your account so that the assets you farm are regularly transferred to your own secured wallet.'
        => 'Пул не является электронным кошельком или банком. Запрещено использовать пул-аккаунты для длительного хранения финансовых активов. Оператор пула не несет ответственности за любую потерю активов, хранящихся в пуле. Вы обязаны настроить свою учетную запись таким образом, чтобы активы, которые вы обрабатываете, регулярно переводились в ваш собственный защищенный кошелек.',
    'While the Pool has an excellent uptime record, there is no uptime guarantee. Users are responsible for configuring their farms so that they will automatically switch to solo mining and/or to other pools in case of downtime.'
        => 'Несмотря на то, что пул имеет отличные показатели непрерывности работы, нет никаких гарантий безотказной работы. Пользователи несут ответственность за настройку своих ферм, чтобы, в случае простоя, они могли автоматически переключаться на соло-майнинг и/или на другие пулы.',
    'Pool accounts are personal, and cannot be sold, traded, bartered or gifted. Multiple accounts controlled by a single entity may be considered as a botnet, and are not welcome. Users suspected of dishonest, fraudulent or illegal activities may be banned without prior notice. In the case of a suspected block withholding attack against the Pool, the Pool Operator may suspend or limit payments to the suspected account(s).'
        => 'Счета пула являются личными, и их нельзя продавать, обменивать или дарить. Несколько учетных записей, контролируемых одним объектом, могут рассматриваться как ботнет и не приветствуются. Пользователи, подозреваемые в нечестной, мошеннической или незаконной деятельности, могут быть заблокированы без предварительного уведомления. В случае атаки на пул с подозрением на удержание блока, оператор пула может приостановить или ограничить выплаты на подозрительный счет.',
    'Accounts which are inactive (no significant farming activity) for longer than a year (365 days) may be permanently deleted. Any remaining balance will be considered as a donation to the Pool.'
        => 'Учетные записи, которые неактивны (не ведется выраженная фермерская деятельность) более года (365 дней), могут быть удалены без возможности восстановления. Любой остаток на балансе будет рассматриваться как пожертвование пулу.',
    'Eligibility'
        => 'Критерий допуска',
    'This Pool is intended solely for users who are eighteen (18) years of age or older. You affirm that you are more than 18 years of age and are competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. You must be 18 years or over to register as a registrant of the Pool. If we discover or have any reason to suspect that you have not reached 18 years of age, then we reserve the right to suspend or terminate your registration to this site immediately and without notice.'
        => 'Этот пул предназначен исключительно для пользователей в возрасте восемнадцати (18) лет и старше. Вы подтверждаете, что вам больше 18 лет, и вы имеете право принимать положения, условия, обязательства, утверждения, заявления и гарантии, изложенные в настоящих Условиях Использования, а также соблюдать и твердо придерживаться настоящих Условий Использования. Вам должно быть 18 лет или больше, чтобы зарегистрироваться в качестве регистранта пула. Если мы обнаружим (или у нас есть основания подозревать), что вам не исполнилось 18 лет, мы оставляем за собой право приостановить или прекратить вашу регистрацию на этом сайте немедленно и без предварительного уведомления.',
    'Legality' => 'Легитимность',
    'You agree the Pool cannot be held liable if laws applicable to you restrict or prohibit your participation. The Pool makes no representations or warranties, implicit or explicit, as to your legal right to participate in any interactive services on the Pool nor shall any person affiliated, or claiming affiliation, with the Pool have authority to make any such representations or warranties, and it is your responsibility to ensure that it is permissible to access and use the Pool. The Pool reserves the right to monitor the location from which you access the Pool and to block access from any jurisdiction in which participation is illegal or restricted.'
        => 'Вы соглашаетесь с тем, что данный пул не несет ответственности, если применимые к вам законы ограничивают или запрещают ваше участие. Пул не делает никаких заявлений или гарантий, явных или подразумеваемых, в отношении вашего законного права участвовать в каких-либо интерактивных услугах в пуле, а также никакое лицо, связанное с пулом или заявляющее о своем участии, не имеет полномочий делать такие заявления или гарантии, и Вы несете ответственность за обеспечение допустимости доступа к пулу и его использования. Пул оставляет за собой право контролировать место, из которого вы получаете доступ к пулу, и блокировать доступ из любой юрисдикции, в которой участие является незаконным или ограниченным.',
    'Questions' => 'Вопросы',
    'If you have questions or would like additional information, please contact us at: info@findchia.com.'
        => 'Если у вас имеются вопросы или вы хотели бы получть дополнительную информацию, Вы можете написать нам на  info@findchia.com. ',
];